development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: angjuly7
  pool: 5
  username: root
  password: 
  
production:
  adapter: mysql2
  encoding: utf8
  host: localhost 
  reconnect: false
  database: angjuly7
  pool: 5
  username: root
  password: 
  
test:
  adapter: mysql2
  encoding: utf8
  host: localhost  
  reconnect: false
  database: angjuly7
  pool: 5
  username: root
  password:   
